/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Pages.Sudhanshu;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javafx.stage.FileChooser;
import javax.swing.JFileChooser;
/**
 *
 * @author Sudhanshu Gangele
 */
public class AgentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AgentJPanel
     */
    public AgentJPanel() {
        initComponents();
        
         //Populate AWT Choices/combobox 
        
        cBoxMedicalHistory.addItem("Diabetes");
        cBoxMedicalHistory.addItem("Heart Ailment");
        cBoxMedicalHistory.addItem("Any other preexisting condition");
        cBoxMedicalHistory.select(0);
        
//        //Choice 2
//        
//        choice2.addItem("None");
//        choice2.select(0);
//      
//        //choice 3
//        
//        choice3.addItem("Everyone on project");
//        choice3.addItem("Team A");
//        choice3.addItem("Team B");
//        choice3.select(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtMobileNo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPlan = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtAnnualIncome = new javax.swing.JTextField();
        btnCalScore = new java.awt.Button();
        txtScore = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        rBtnMale = new javax.swing.JRadioButton();
        rBtnFemale = new javax.swing.JRadioButton();
        cBoxMedicalHistory = new java.awt.Choice();
        txtFileNo = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        btn_close = new javax.swing.JLabel();
        btnSendAth = new java.awt.Button();
        jPanel11 = new javax.swing.JPanel();
        txtcustomerName = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1370, 680));
        setPreferredSize(new java.awt.Dimension(1370, 680));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 190, 121)));
        jPanel4.setForeground(new java.awt.Color(255, 182, 25));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(12, 115, 101));
        jLabel8.setText("First Name");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 23, -1, -1));

        txtFirstName.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                txtFirstNameComponentMoved(evt);
            }
        });
        jPanel4.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 23, 127, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(12, 115, 101));
        jLabel11.setText("Date Of Birth");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 83, -1, -1));
        jPanel4.add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 85, 127, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(12, 115, 101));
        jLabel12.setText("Annual Income");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 204, -1, -1));
        jPanel4.add(txtMobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 149, 127, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(12, 115, 101));
        jLabel13.setText("Plan");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 204, 92, -1));
        jPanel4.add(txtPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 206, 127, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(12, 115, 101));
        jLabel20.setText("Address");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 147, 65, -1));
        jPanel4.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 149, 92, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(12, 115, 101));
        jLabel21.setText("Medical History");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 262, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(12, 115, 101));
        jLabel22.setText("Last Name");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 21, 75, -1));
        jPanel4.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 23, 92, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(12, 115, 101));
        jLabel23.setText("Mobile");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 147, 65, -1));
        jPanel4.add(txtAnnualIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 206, 92, -1));

        btnCalScore.setBackground(new java.awt.Color(16, 190, 121));
        btnCalScore.setForeground(new java.awt.Color(255, 255, 255));
        btnCalScore.setLabel("Calcuate Score");
        btnCalScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalScoreActionPerformed(evt);
            }
        });
        jPanel4.add(btnCalScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 109, 40));

        txtScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScoreActionPerformed(evt);
            }
        });
        jPanel4.add(txtScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 94, 40));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(12, 115, 101));
        jLabel24.setText("Gender");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 83, 75, -1));

        rBtnMale.setBackground(new java.awt.Color(255, 255, 255));
        rBtnMale.setText("Male");
        rBtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnMaleActionPerformed(evt);
            }
        });
        jPanel4.add(rBtnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 84, -1, -1));

        rBtnFemale.setBackground(new java.awt.Color(255, 255, 255));
        rBtnFemale.setText("Female");
        jPanel4.add(rBtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 84, -1, -1));

        cBoxMedicalHistory.setName(""); // NOI18N
        jPanel4.add(cBoxMedicalHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 262, 127, -1));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 720, 460));

        txtFileNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtFileNo.setForeground(new java.awt.Color(12, 115, 101));
        txtFileNo.setText("1001");
        add(txtFileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 80, 41));

        jPanel15.setBackground(new java.awt.Color(12, 115, 101));

        btn_close.setBackground(new java.awt.Color(96, 83, 150));
        btn_close.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        btn_close.setForeground(new java.awt.Color(255, 255, 255));
        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_delete_50px.png"))); // NOI18N
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(0, 230, Short.MAX_VALUE)
                .addComponent(btn_close))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_close, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 230, 70));

        btnSendAth.setBackground(new java.awt.Color(16, 190, 121));
        btnSendAth.setForeground(new java.awt.Color(255, 255, 255));
        btnSendAth.setLabel("Send for Authorization");
        btnSendAth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendAthActionPerformed(evt);
            }
        });
        add(btnSendAth, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 600, 130, 40));

        jPanel11.setBackground(new java.awt.Color(16, 190, 121));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1340, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 1340, -1));

        txtcustomerName.setBackground(new java.awt.Color(41, 216, 95));
        txtcustomerName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtcustomerName.setForeground(new java.awt.Color(12, 115, 101));
        txtcustomerName.setText(" Dino Konstantopolos");
        add(txtcustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 190, 30));

        jLabel14.setBackground(new java.awt.Color(41, 216, 95));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(12, 115, 101));
        jLabel14.setText("Details for ");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 100, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(12, 115, 101));
        jLabel9.setText("File Number : ");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 80, 41));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalScoreActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnCalScoreActionPerformed

    private void txtScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScoreActionPerformed

    private void rBtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBtnMaleActionPerformed

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_closeMouseClicked

    private void btnSendAthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendAthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSendAthActionPerformed

    private void txtFirstNameComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtFirstNameComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameComponentMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnCalScore;
    private java.awt.Button btnSendAth;
    private javax.swing.JLabel btn_close;
    private java.awt.Choice cBoxMedicalHistory;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton rBtnFemale;
    private javax.swing.JRadioButton rBtnMale;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAnnualIncome;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JLabel txtFileNo;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMobileNo;
    private javax.swing.JTextField txtPlan;
    private javax.swing.JTextField txtScore;
    private javax.swing.JLabel txtcustomerName;
    // End of variables declaration//GEN-END:variables
//    
//    private java.awt.Choice choice2;
//    private java.awt.Choice choice3;
}
