/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Pages.hospitalEnterprise.LabAssistant;

import Business.Billing.Bill;
import Business.Customer.Patient;
import Business.Departments.Organization;
import Business.Enterprises.Enterprise;
import Business.Medical.MedicalReport;
import Business.WorkQueue.BillingWorkRequest;

import Business.WorkQueue.BuyInsuranceWorkRequest;
import Business.WorkQueue.CustomerLabWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author madhav437
 */
public class LabProcess extends javax.swing.JPanel {

    /**
     * Creates new form BillingPage1
     */
    JPanel rightPanel;
    CustomerLabWorkRequest lReq;
    public LabProcess(JPanel rightPanel,CustomerLabWorkRequest lReq) {
        initComponents();
        this.rightPanel =  rightPanel;
        this.lReq = lReq;
        fillScreen();
       
        
    }
    
    void fillScreen(){
         Patient pat = (Patient) lReq.getSender();
         outPatientName.setText(pat.getfName() + " " +  pat.getLastName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        btn_close = new javax.swing.JLabel();
        outPatientName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        outGlucFast = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        createLabReport = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        outGlucPost = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        outHemo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        outCreat = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        outCholestrol = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(247, 247, 247));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(96, 83, 150));
        jLabel5.setText("Medical Report");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 24, 220, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(96, 83, 150));
        jLabel7.setText("Patient details");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 78, 115, 26));

        jPanel7.setBackground(new java.awt.Color(247, 247, 247));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 164, -1, -1));

        jPanel15.setBackground(new java.awt.Color(96, 83, 150));

        btn_close.setBackground(new java.awt.Color(96, 83, 150));
        btn_close.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_close.setForeground(new java.awt.Color(255, 255, 255));
        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_close_window_52px_2.png"))); // NOI18N
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_closeMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(btn_close)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_close, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(942, 6, -1, -1));

        outPatientName.setEditable(false);
        add(outPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 79, 290, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(96, 83, 150));
        jLabel15.setText("Submit Medical Test");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 282, 166, -1));

        jPanel12.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 65, 900, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(96, 83, 150));
        jLabel8.setText("Normal Range : < 100 mg/dL");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 111, 253, 26));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Images/icons8-american_express.png"))); // NOI18N
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 11, -1, -1));
        add(outGlucFast, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 112, 146, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8-test_tube_rack.png"))); // NOI18N
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 11, -1, -1));

        createLabReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Pages/images/icons8-treatment.png"))); // NOI18N
        createLabReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createLabReportActionPerformed(evt);
            }
        });
        add(createLabReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 317, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(96, 83, 150));
        jLabel9.setText("Glucose (Post)");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 144, 115, 26));
        add(outGlucPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 145, 146, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(96, 83, 150));
        jLabel10.setText("Hemoglobin");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 177, 115, 26));
        add(outHemo, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 178, 146, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(96, 83, 150));
        jLabel11.setText("Creatinine");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 210, 115, 26));
        add(outCreat, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 211, 146, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(96, 83, 150));
        jLabel13.setText("Cholesterol");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 237, 115, 26));
        add(outCholestrol, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 238, 146, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(96, 83, 150));
        jLabel14.setText("Glucose (Fast)");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 111, 115, 26));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(96, 83, 150));
        jLabel17.setText("Normal Range : < 140 mg/dL");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 144, 253, 26));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(96, 83, 150));
        jLabel18.setText("Normal Range : 14 to 18 gm/dL  ");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 179, 482, 26));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(96, 83, 150));
        jLabel19.setText("Normal Range : 0.6 to 1.2 (mg)/(dL)");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 210, 281, 26));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(96, 83, 150));
        jLabel20.setText("Normal Range : < 200 mg/dL");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 237, 253, 26));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        //System.exit(0);
        
        
            Component[] comps = this.rightPanel.getComponents();
        for(Component comp: comps){
            if(comp instanceof Lab_Home){
                Lab_Home lHome = (Lab_Home) comp;
                lHome.populateLabTable();
                //manageAdmin.init();
            }
        }
        
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        rightPanel.remove(this);
        layout.previous(rightPanel);
    }//GEN-LAST:event_btn_closeMouseClicked

    private void createLabReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createLabReportActionPerformed
        // TODO add your handling code here:
        
        
         try{
            Float.parseFloat(outGlucFast.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Please enter a number for Glucose Fasting");
              return;  
            }
         
         try{
            Float.parseFloat(outGlucPost.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Please enter a number for Glucose Post Lunch");
              return;  
            }
         
         try{
           Float.parseFloat(outHemo.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Please enter a number for Hemoglobin");
              return;  
            }
         
         try{
           Float.parseFloat(outCreat.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Please enter a number for Creatinine");
              return;  
            }
         
         try{
            Float.parseFloat(outCholestrol.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Please enter a number for Cholestrol level");
              return;  
            }
        
        //MedicalReport mr = Patient.getMedicalHistory.createMedicalReport();
        HashMap<String, String> hmap1 = new HashMap<String, String>();
          
          hmap1.put("Glucose Fast", outGlucFast.getText()); 
          hmap1.put("Glucose Post", outGlucPost.getText());
          hmap1.put("Hemoglobin", outHemo.getText());
          hmap1.put("Creatinin", outCreat.getText());
          hmap1.put("Cholestrol", outCholestrol.getText());
          
          
          // Check if one of the vitals abnormal
          
          char abNormal = ' ';
          
          if (Float.parseFloat(outGlucFast.getText()) > 100 ||
              Float.parseFloat(outGlucPost.getText()) > 140 ||
              Float.parseFloat(outHemo.getText()) < 14 ||
              Float.parseFloat(outHemo.getText())> 18 ||
              Float.parseFloat(outCreat.getText()) > 1.2 ||
              Float.parseFloat(outCreat.getText()) < 0.6 ||
              Float.parseFloat(outCholestrol.getText()) > 200)
              
              abNormal = 'Y';
                  
          
              Patient pat = (Patient) lReq.getSender();
          
         // mr.setTestParameters(hmap1);
         
         
         
         
         MedicalReport medRep = pat.getMedHist().createMedReport();
         medRep.setPatient(pat.getfName() + " "+  pat.getLastName());
         medRep.setTestParameters(hmap1);
         Date date = new Date();
         medRep.setDate(String.valueOf(date));
         
         lReq.setStatus("Processed");
         
         JOptionPane.showMessageDialog(null, "Medical Report Saved");
         
         
         // If Lab test is from Insurance - Send it to Insurance
         String str = lReq.getWorkRequestType();
         String str1 = "Tests For Insurance";
         
         if(str.equals(str1)){
             
             //Write Code to Update Buy Work Request for Patient to the 
             Organization patInsOrg = pat.getInsuranceOrganization();
             for ( WorkRequest wr : patInsOrg.getWorkQueue().getWorkRequestList()){
             BuyInsuranceWorkRequest br = (BuyInsuranceWorkRequest) wr;
             
             Patient pat1 =  br.getPatient();
             if(pat1 == pat){
                 
             if(abNormal == 'Y')
             
             br.setTestResult("Abnormal");
                 else
             br.setTestResult("Normal");
             br.setStatus("Test Result Updated");
             break;
             }   
      
             }
      
         }
         
         if(!str.equals(str1)){
             
             // Generate Bill
             
             //Check if Patient has insurance
             
             if (!pat.getInsDetail().equals(" ")){
                 Enterprise e1 = pat.getInsCompany();
             
                for(Organization org :e1.getOrganizationDirectory().getOrganizationList()){
                    if (org.getOrganizationType().equals("Claims Organization")){
                        
                        BillingWorkRequest bWR  = new BillingWorkRequest();
                        bWR.setPatient(pat);
                        bWR.setRequestDate(date);
                        bWR.setClaimedAmount("250");
                        bWR.setMessage("Tests");
                        org.getWorkQueue().getWorkRequestList().add(bWR);
                        
                        
                        
                    }
                        
                       
                    }
                }
             else{
                 
                 //Add Bill to the patient
                 
                 Bill b1 = new Bill();
                 //b1.setAppointment(appointment);
                 b1.setBillType("Self Pay");
                 b1.setBillAmount("250");
                 b1.setPaidThroughSelf(250);
                 pat.getBillHist().getBillingHistory().add(b1);
                 
                 
             
             
             }
             
         
         }
         
         
         
         outCholestrol.setText(" ");
         outGlucFast.setText(" " );
         outGlucPost.setText(" ");
         outCreat.setText(" ");
         outCholestrol.setText(" ");
         outHemo.setText(" ");
         
          
         Component[] comps = this.rightPanel.getComponents();
        for(Component comp: comps){
            if(comp instanceof Lab_Home){
                Lab_Home lHome = (Lab_Home) comp;
                lHome.populateLabTable();
                //manageAdmin.init();
            }
        }
        
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        rightPanel.remove(this);
        layout.previous(rightPanel);
        
      
        
        
        
    }//GEN-LAST:event_createLabReportActionPerformed

    private void btn_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_closeMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_close;
    private javax.swing.JButton createLabReport;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField outCholestrol;
    private javax.swing.JTextField outCreat;
    private javax.swing.JTextField outGlucFast;
    private javax.swing.JTextField outGlucPost;
    private javax.swing.JTextField outHemo;
    private javax.swing.JTextField outPatientName;
    // End of variables declaration//GEN-END:variables
}
