/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Business.Airliners.Airliner;
import Business.Airliners.Airplane;
import Business.Airliners.Flight;
import Business.Airliners.FlightDates;
import Business.TravelOffice.MainTravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rohit
 */
public class AddFlightSchedule extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewAirlinerPanel
     */
    
//    Airliner airliner;
    MainTravelAgency mainTravelAgency;
    JPanel displayPanel;
    
    Airplane aircraft;

    
    public AddFlightSchedule(Airplane aircraft,MainTravelAgency mainTravelAgency, JPanel displayPanel) {
        initComponents();
        this.displayPanel = displayPanel;
        this.mainTravelAgency = mainTravelAgency;
        this.aircraft = aircraft;
        
        aircraftNameTxt.setText(aircraft.getName());
        AircraftCodeTxt.setText(aircraft.getType());
        
        buttonGroup1.add(specificDateRadBtn);
        buttonGroup1.add(scheduleRadio);
        
        specificDates.setVisible(false);
        scheduleTxt.setVisible(false);    
        infoLabel.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        destTxt = new javax.swing.JTextField();
        timeTxt = new javax.swing.JTextField();
        originTxt = new javax.swing.JTextField();
        specificDates = new org.jdesktop.swingx.JXDatePicker();
        specificDateRadBtn = new javax.swing.JRadioButton();
        scheduleRadio = new javax.swing.JRadioButton();
        scheduleTxt = new javax.swing.JTextField();
        infoLabel = new javax.swing.JLabel();
        aircraftNameTxt = new javax.swing.JTextField();
        AircraftCodeTxt = new javax.swing.JTextField();
        flightNumTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addScheduleBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        priceTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        warningFlightNumberLbl = new javax.swing.JLabel();
        warningOriginLbl = new javax.swing.JLabel();
        warningDestLbl = new javax.swing.JLabel();
        warningtTckLbl = new javax.swing.JLabel();
        warningSpecificLbl = new javax.swing.JLabel();
        warningSchLbl = new javax.swing.JLabel();
        warningtimeLbl = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel1.setText("<html><font size=5> <u> <b> Add Flight Schedule ");

        jLabel2.setText("Origin City :");

        jLabel3.setText("Destination City :");

        jLabel4.setText("Ticket Price :");

        jLabel5.setText("Flight Details :");

        specificDateRadBtn.setText("Specific Date");
        specificDateRadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specificDateRadBtnActionPerformed(evt);
            }
        });

        scheduleRadio.setText("Schedule");
        scheduleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleRadioActionPerformed(evt);
            }
        });

        infoLabel.setText("<html>  ^ <i> flies for these many days");

        jLabel7.setText("Flight Number :");

        addScheduleBtn.setText("Add Schedule");
        addScheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addScheduleBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<<");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Time :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(flightNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(originTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(destTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scheduleRadio)
                                    .addComponent(specificDateRadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(specificDates, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(scheduleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addScheduleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(timeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(warningFlightNumberLbl)
                                    .addComponent(warningOriginLbl)
                                    .addComponent(warningDestLbl)
                                    .addComponent(warningtTckLbl)))
                            .addComponent(warningtimeLbl)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(warningSpecificLbl)
                                    .addComponent(warningSchLbl)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(aircraftNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AircraftCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aircraftNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AircraftCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningFlightNumberLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(flightNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(originTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(destTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(warningOriginLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(specificDateRadBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scheduleRadio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(specificDates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scheduleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(warningDestLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(warningtTckLbl)
                                .addGap(36, 36, 36)
                                .addComponent(warningSpecificLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(warningSchLbl)
                                .addGap(62, 62, 62)
                                .addComponent(warningtimeLbl)))))
                .addGap(18, 18, 18)
                .addComponent(addScheduleBtn)
                .addContainerGap(181, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void specificDateRadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specificDateRadBtnActionPerformed
        specificDates.setVisible(true);
        scheduleTxt.setVisible(false);
        
        infoLabel.setVisible(false);
    }//GEN-LAST:event_specificDateRadBtnActionPerformed

    private void scheduleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleRadioActionPerformed
        specificDates.setVisible(false);

        infoLabel.setVisible(true);
        scheduleTxt.setVisible(true);
    }//GEN-LAST:event_scheduleRadioActionPerformed

    private void addScheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addScheduleBtnActionPerformed
        String flightNum = flightNumTxt.getText();
        String origin = originTxt.getText();
        String dest = destTxt.getText();
        Date d1 = specificDates.getDate();
        int i = 0;
        float time = 0.0F;
        double price = 0.0;
        try{
         i = Integer.parseInt(scheduleTxt.getText());
        }
        catch(Exception e){
            warningSchLbl.setVisible(true);
            warningSchLbl.setText("Invalid Characters. Please enter a number.");            
        
        }
        try{
         time = Float.parseFloat(timeTxt.getText());        
        }
        catch(Exception e){
            warningtimeLbl.setVisible(true);
            warningtimeLbl.setText("Invalid time. Use 24-hour clock digit seperated by a dot ( . )  ");            
            
        
        }
        try{
         price = Double.parseDouble(priceTxt.getText());
        }
        catch(Exception e){
            warningtTckLbl.setVisible(true);
            warningtTckLbl.setText("Invalid price. Please enter correct number.");
            
        }
        
        
        if(origin.length() == 0){
            
            warningOriginLbl.setVisible(true);
            warningOriginLbl.setText("Origin City cannot be empty");
        
        
        }
        else{
            warningOriginLbl.setVisible(false);
            warningOriginLbl.setText("Origin City cannot be empty");
        }
        
        if(dest.length() == 0){
            warningDestLbl.setVisible(true);
            warningDestLbl.setText("Destination City cannot be empty");        
        
        }
        
        else{
            warningDestLbl.setVisible(false);
            warningDestLbl.setText("Origin City cannot be empty");              
        }
        
        
        if((origin.length() != 0) &&
            (dest.length() != 0) &&
                (price != 0) && (d1 != null || i != 0) &&
                (time != 0) &&
                (flightNum.length() != 0)
                ){
            
            
            if(d1 != null && i == 0){
                FlightDates flightdate = new FlightDates(d1, time, aircraft.getNoOfSeats());
                aircraft.getFlightDetails().setFlightSchedule(flightNum, origin,  dest, price, flightdate);
                    JOptionPane.showMessageDialog(null, "Successfully added!");
            }
            else if(d1 == null && i != 0)
            {
                Date d2 = new Date();
                for(int j = 0; j < i; j++)
                {
                    d2 = getNextDate(d2);
                    FlightDates flightdate = new FlightDates(d2, time, aircraft.getNoOfSeats());
                    aircraft.getFlightDetails().setFlightSchedule(flightNum, origin,  dest, price, flightdate);         
                
                }
                    JOptionPane.showMessageDialog(null, "Successfully added!");
            }
        }

    }//GEN-LAST:event_addScheduleBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

                Component[] comps = this.displayPanel.getComponents();
        for(Component comp: comps){
            if(comp instanceof ViewAircraftDetails){
                ViewAircraftDetails viewAircraftDet = (ViewAircraftDetails) comp;
                viewAircraftDet.populate();
            
            }
        
        
        }
        
        CardLayout layout = (CardLayout)displayPanel.getLayout();
        displayPanel.remove(this);
        layout.previous(displayPanel);
        
        
        
        
        
        

        
        
        
        
        
        
        
        
    }//GEN-LAST:event_backBtnActionPerformed
    public static Date getNextDate(Date  curDate) {
      final Calendar calendar = Calendar.getInstance();
      calendar.setTime(curDate);
      calendar.add(Calendar.DAY_OF_YEAR, 1);
      return  calendar.getTime(); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AircraftCodeTxt;
    private javax.swing.JButton addScheduleBtn;
    private javax.swing.JTextField aircraftNameTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField destTxt;
    private javax.swing.JTextField flightNumTxt;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField originTxt;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JRadioButton scheduleRadio;
    private javax.swing.JTextField scheduleTxt;
    private javax.swing.JRadioButton specificDateRadBtn;
    private org.jdesktop.swingx.JXDatePicker specificDates;
    private javax.swing.JTextField timeTxt;
    private javax.swing.JLabel warningDestLbl;
    private javax.swing.JLabel warningFlightNumberLbl;
    private javax.swing.JLabel warningOriginLbl;
    private javax.swing.JLabel warningSchLbl;
    private javax.swing.JLabel warningSpecificLbl;
    private javax.swing.JLabel warningtTckLbl;
    private javax.swing.JLabel warningtimeLbl;
    // End of variables declaration//GEN-END:variables
}
