/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Business.Airliners.Airliner;
import Business.TravelOffice.MainTravelAgency;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rohit
 */
public class ManageAirlinersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirlinersJPanel
     */
    
    JPanel displayPanel;
    MainTravelAgency mainTravelAgency;
    
    
    public ManageAirlinersJPanel(JPanel displayPanel, MainTravelAgency mainTravelAgency) {
        initComponents();
        this.mainTravelAgency = mainTravelAgency;
        this.displayPanel = displayPanel;
        populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDirectory = new javax.swing.JTable();
        viewAirlineBtn = new javax.swing.JButton();
        addAirlineBtn = new javax.swing.JButton();
        searchFieldTxt = new javax.swing.JTextField();
        searchAirlinerBtn = new javax.swing.JButton();
        deleteAirline = new javax.swing.JButton();

        jLabel1.setText("<html> <font size=5> <b> <u> Manage Airliners");

        tblDirectory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Airliners Name", "Airliners Code"
            }
        ));
        jScrollPane1.setViewportView(tblDirectory);

        viewAirlineBtn.setText("View Airlines Details");
        viewAirlineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAirlineBtnActionPerformed(evt);
            }
        });

        addAirlineBtn.setText("Add New Airlines");
        addAirlineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAirlineBtnActionPerformed(evt);
            }
        });

        searchAirlinerBtn.setText("Search Airliner");
        searchAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAirlinerBtnActionPerformed(evt);
            }
        });

        deleteAirline.setText("Delete Airline");
        deleteAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAirlineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(searchFieldTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(searchAirlinerBtn))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(viewAirlineBtn)
                        .addComponent(addAirlineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deleteAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchAirlinerBtn)
                    .addComponent(searchFieldTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(viewAirlineBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addAirlineBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteAirline)
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewAirlineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAirlineBtnActionPerformed
        int selectedRow = tblDirectory.getSelectedRow();
        if(selectedRow >= 0)
        {            
            Airliner airliner = (Airliner) tblDirectory.getValueAt(selectedRow, 0);
            ViewAirlinerJPanel viewAirliner = new ViewAirlinerJPanel(airliner, mainTravelAgency, this.displayPanel);
            displayPanel.add("viewAirliner", viewAirliner);
            CardLayout layout = (CardLayout) this.displayPanel.getLayout();
            layout.next(displayPanel);
  
        }   

    }//GEN-LAST:event_viewAirlineBtnActionPerformed

    private void addAirlineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAirlineBtnActionPerformed
        AddNewAirlinerPanel airlinePanel = new AddNewAirlinerPanel(displayPanel, mainTravelAgency);
        displayPanel.add("CreateAircraftJPanel", airlinePanel);
        CardLayout layout = (CardLayout) this.displayPanel.getLayout();
        layout.next(displayPanel);

                            
        
    }//GEN-LAST:event_addAirlineBtnActionPerformed

    private void searchAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAirlinerBtnActionPerformed
        
        String s = searchFieldTxt.getText();

        if(!(s.length() == 0)){
            DefaultTableModel dtm = (DefaultTableModel)tblDirectory.getModel();
            dtm.setRowCount(0);

            for(Airliner airliner : this.mainTravelAgency.searchAirliners(s)){
                Object[] row = new Object[dtm.getColumnCount()];
                row[0]=airliner;
                row[1]=airliner.getAirlineCode();
                dtm.addRow(row);
            }
        }
        
        else{
            populate();
       
        }   
    }//GEN-LAST:event_searchAirlinerBtnActionPerformed

    private void deleteAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAirlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteAirlineActionPerformed

    public void populate(){
        DefaultTableModel dtm = (DefaultTableModel)tblDirectory.getModel();
        dtm.setRowCount(0);
        
        for(Airliner a : mainTravelAgency.getAirliners()){
            Object[] row = new Object[dtm.getColumnCount()];
         
            row[0]=a;
            row[1]=a.getAirlineCode();
            dtm.addRow(row);
        }
    }
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAirlineBtn;
    private javax.swing.JButton deleteAirline;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton searchAirlinerBtn;
    private javax.swing.JTextField searchFieldTxt;
    private javax.swing.JTable tblDirectory;
    private javax.swing.JButton viewAirlineBtn;
    // End of variables declaration//GEN-END:variables
}
